### ISSUE TITLE
Bug: Missing Dependency - actiontext

### ISSUE THREAD

**Issue by pboling** [pantographe/view_component-form#111]
https://rubygems.org/gems/actiontext/versions

Need to add to gemspec:
```
  spec.add_dependency "actiontext", [">= 6.0.0", "< 7.1"]
```

There is a hard dependency on `actiontext` here:
https://github.com/pantographe/view_component-form/blob/main/app/components/view_component/form/rich_text_area_component.rb#L6

**Comment by pboling** [comment]
@Spone does this make sense?  Looks like this is related to #47 - which makes me wonder if not declaring the `actiontext` dependency is intentional?  And in that case, perhaps the change should be one of documentation?

**Comment by tmaier** [comment]
Since I am not using `actiontext` at all, I disabled it among other things in my application.

<details>
<summary>
Excerpt from application.rb
</summary>

```ruby
# frozen_string_literal: true

require_relative 'boot'

require 'rails'
# Pick the frameworks you want:
require 'active_model/railtie'
require 'active_job/railtie'
require 'active_record/railtie'
# require "active_storage/engine"
require 'action_controller/railtie'
require 'action_mailer/railtie'
# require "action_mailbox/engine"
# require "action_text/engine"
require 'action_view/railtie'
require 'action_cable/engine'
# require "sprockets/railtie"
require 'rails/test_unit/railtie'
```
</details>

I would not like to have this like a strong dependency.
I would especially not like it, if it require automatically `action_text`

Instead, it should behave similarly to what you propose for `country_select` at #41: Only provide that helper, if `defined?(ActionView::Helpers::Tags::ActionText)`

**Comment by pboling** [comment]
@tmaier In that case you would prefer the solution here - https://github.com/pantographe/view_component-form/pull/109

I think that's reasonable.  I'll close this in favor of that solution.
